const ACTION_TYPES = {
  ADD_POST: 'ADD_POST',
  UPDATE_POST: 'UPDATE_POST',
  ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
  UPDATE_NEW_MESSAGE: 'UPDATE_NEW_MESSAGE',
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLW',
  SET_USERS: 'SET_USERS',
};

export default ACTION_TYPES;
